Repository mdsreq-fga-unb/2023.2-NutriPlanner, pull requests merged in 2023-10, with the labels that each got.

#14 Correções realizadas
  docs/visao_geral_produto/visao_produto.md
Labels: documentation, improvement

#15 docs: Alteração do diagrama de Ishikawa
  docs/visao_geral_produto/assets/images/Ishikawa.jpeg
  docs/visao_geral_produto/assets/images/Ishikawa.png
  docs/visao_geral_produto/visao_produto.md
Labels: improvement

#17 [#07] Correção de problema em visão do produto.
  docs/visao_geral_produto/visao_produto.md
Labels: documentation

#18 [Fix] Arrumando atribuições
  docs/visao_projeto/visao_do_projeto.md
Labels: documentation

#23 Adicionando Toques finais -> Entrega Unidade 02
  docs/produto/backlog/backlog_safe.md
  docs/produto/mvp/prop_mvp.md
  docs/videos/videos.md
Labels: enhancement
