Repository mdsreq-fga-unb/2023.2-NutriPlanner, pull requests merged in 2023-11, with the labels that each got.

#32 Adição dos Produtos de Matriz de Comunicação no GitHub Pages
  docs/atas_reunioes_gerais/ata_1.md
  docs/atas_reunioes_gerais/ata_2.md
  docs/atas_reunioes_gerais/ata_3.md
  docs/atas_reunioes_gerais/ata_4.md
  docs/atas_reunioes_gerais/ata_5.md
  docs/atas_reunioes_gerais/ata_6.md
  docs/atas_reunioes_gerais/ata_7.md
  docs/relatorios_consideracoes_cliente/relatorio-08-10-2023.md
  docs/relatorios_consideracoes_cliente/relatorio-09-11-2023.md
  mkdocs.yml
Labels: documentation, enhancement

#27 Correção diagrama de Ishikawa
  docs/visao_geral_produto/assets/images/Ishikawa.png
Labels: documentation

#30 [improve] Tabela MVP
  docs/docs_separados/historia.md
  docs/produto/mvp/1.jpg
  docs/produto/mvp/2.jpg
  docs/produto/mvp/3.jpg
  docs/produto/mvp/4.jpg
  docs/produto/mvp/5.jpg
  docs/produto/mvp/prop_mvp.md
  docs/videos/videos.md
  mkdocs.yml
Labels: documentation, enhancement

#29 [fix] Correção referente issue #10
  docs/visao_projeto/visao_do_projeto.md
Labels: documentation

#33 [add] templates de sprint
  docs/templates/SUPER-R - Template - Planning Meeting.pdf
  docs/templates/SUPER-R - Template - Retrospective Meeting.pdf
  docs/templates/SUPER-R - Template - Review Meeting.pdf
Labels: documentation

#36 fix(mvp):remove US01 do mvp
  docs/produto/mvp/prop_mvp.md
Labels: documentation

#37 Merge branch Develop to Main
  docs/atas_reunioes_gerais/ata_1.md
  docs/atas_reunioes_gerais/ata_2.md
  docs/atas_reunioes_gerais/ata_3.md
  docs/atas_reunioes_gerais/ata_4.md
  docs/atas_reunioes_gerais/ata_5.md
  docs/atas_reunioes_gerais/ata_6.md
  docs/atas_reunioes_gerais/ata_7.md
  docs/docs_separados/historia.md
  docs/produto/backlog/backlog_safe.md
  docs/produto/mvp/1.jpg
  docs/produto/mvp/2.jpg
  docs/produto/mvp/3.jpg
  docs/produto/mvp/4.jpg
  docs/produto/mvp/5.jpg
  docs/produto/mvp/prop_mvp.md
  docs/relatorios_consideracoes_cliente/relatorio-08-10-2023.md
  docs/relatorios_consideracoes_cliente/relatorio-09-11-2023.md
  docs/stylesheets/styles.css
  docs/templates/SUPER-R - Template - Planning Meeting.pdf
  docs/templates/SUPER-R - Template - Retrospective Meeting.pdf
  docs/templates/SUPER-R - Template - Review Meeting.pdf
  docs/videos/videos.md
  docs/visao_geral_produto/assets/images/Ishikawa.png
  docs/visao_geral_produto/visao_produto.md
  docs/visao_projeto/visao_do_projeto.md
  mkdocs.yml
Labels: documentation, enhancement

#38 fix(planejamento de fases): Modifica frequência das atividades
  docs/visao_projeto/visao_do_projeto.md
Labels: documentation

#39 Develop to main
  docs/visao_projeto/visao_do_projeto.md
Labels: documentation

#40 [DOCUMENTAÇÃO] Definição de Padrões para Commits e Pull Requests
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/user-story-template.md
  .github/pull_request_template.md
  README.md
Labels: documentation

#46 docs(dor e dod): adiciona checklist
  docs/produto/dod/dod.md
  docs/produto/dor/dor.md
  mkdocs.yml
Labels: documentation

#47 doc(ciclos): Atualiza tabela
  docs/visao_projeto/visao_do_projeto.md
Labels: enhancement

#49 doc(criterios): add tabela de critérios
  docs/produto/criterios_aceit/criterios.md
  mkdocs.yml
Labels: documentation

#48 Adição do USM ao Pages
  docs/docs_separados/assets/USM - Foto 1.png
  docs/docs_separados/assets/USM - Foto 2.png
  docs/docs_separados/assets/USM - Foto 3.png
  docs/docs_separados/usm.md
  mkdocs.yml
Labels: documentation

#50 Adiciona PBB ao GitPages
  docs/docs_separados/assets/PBB_Expectativas.png
  docs/docs_separados/assets/PBB_Funcionalidades1.png
  docs/docs_separados/assets/PBB_Funcionalidades2.png
  docs/docs_separados/assets/PBB_Funcionalidades3.png
  docs/docs_separados/assets/PBB_Funcionalidades4.png
  docs/docs_separados/assets/PBB_Funcionalidades5.png
  docs/docs_separados/assets/PBB_PBI1.png
  docs/docs_separados/assets/PBB_PBI2.png
  docs/docs_separados/assets/PBB_PBI3.png
  docs/docs_separados/assets/PBB_PBI4.png
  docs/docs_separados/assets/PBB_PBI5.png
  docs/docs_separados/assets/PBB_Personas1.png
  docs/docs_separados/assets/PBB_Personas2.png
  docs/docs_separados/assets/PBB_Personas3.png
  docs/docs_separados/assets/PBB_Problemas.png
  docs/docs_separados/assets/PBB_US1.png
  docs/docs_separados/assets/PBB_US2.png
  docs/docs_separados/assets/PBB_US3.png
  docs/docs_separados/assets/PBB_US4.png
  docs/docs_separados/assets/PBB_US5.png
  docs/docs_separados/pbb.md
  mkdocs.yml
Labels: documentation

#51 doc(verival): add tabela GL
  docs/docs_separados/bdd.md
  docs/docs_separados/verival_gl.md
  mkdocs.yml
Labels: documentation

#61 Update README documentação
  README.md
Labels: documentation, enhancement

#62 [US24] - Envio de Email ao Paciente
  .env.example
  backend/.env
  backend/package-lock.json
  backend/package.json
  backend/src/enviarEmail.js
  backend/src/script.js
  backend/src/server.js
Labels: enhancement, US, backend
